### ISSUE TITLE
把vue依赖从dependencies迁移到peerDependencies

### ISSUE THREAD

**Issue by latte03** [ambit-tsai/vue2-helpers#13]
可以把 vue 从dependencies改到peerDependencies么。毕竟用这个插件的话，都会用本地的vue，因为插件本身dependencies带有vue，导致我这边使用的时候无法获取到正确的结果

**Comment by ambit-tsai** [comment]
你说的是 v1 版本还是 v2，问题能否再补充些细节

**Comment by latte03** [comment]
> 你说的是 v1 版本还是 v2，问题能否再补充些细节

v2的，在模块联邦的host项目中，shared：["vue"] ，使用 store 或者router helper 就会报错不在setup环境下
