### ISSUE TITLE
useRouter is undefined in Vue 2.7.11

### ISSUE THREAD

**Issue by mbokil** [ambit-tsai/vue2-helpers#14]
I upgraded to the latest Vue 2.7.11 and I get the error: 
Cannot read properties of undefined (reading '_router')

My current work around is to call useRouter on mounted in script setup to avoid the undefined error.

```
onMounted(() => {
 router = useRouter();
})
```

**Comment by ambit-tsai** [comment]
Fix in vue2-helpers@**2.1.1**

Vue 2.7.11 moves the invocation of setup to before the invocation of beforeCreate.
See https://github.com/vuejs/vue/commit/e1342df7847a51c75192fec74e94378178e046b0

**Comment by mbokil** [comment]
Thanks you are so fast. Much appreciated!
